

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getTreeDocumentContent: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/content/documentlists/{documentListName}/documentTree/{documentName}/content'
	}),
	transformTreeDocumentContent: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/content/documentlists/{documentListName}/documentTree/{documentName}/transform?width={width}&height={height}&maxWidth={maxWidth}&maxHeight={maxHeight}&crop={crop}&quality={quality}'
	}),
	getTreeDocument: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/content/documentlists/{documentListName}/documentTree/{documentName}?includeInactive={includeInactive}&responseFields={responseFields}'
	}),
	updateTreeDocumentContent: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/content/documentlists/{documentListName}/documentTree/{documentName}/content?folderPath={folderPath}&folderId={folderId}'
	}),
	deleteTreeDocumentContent: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/content/documentlists/{documentListName}/documentTree/{documentName}/content?folderPath={folderPath}&folderId={folderId}'
	})
});
