

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	create: Client.method({
		method: constants.verbs.POST,
		url: '{+pciPod}payments/commerce/payments/cards/?responseFields={responseFields}'
	}),
	getGiftCardBalance: Client.method({
		method: constants.verbs.POST,
		url: '{+pciPod}payments/commerce/payments/cards/{cardId}/balance?responseFields={responseFields}'
	}),
	getUnregisteredGiftCardBalance: Client.method({
		method: constants.verbs.POST,
		url: '{+pciPod}payments/commerce/payments/cards/balance?responseFields={responseFields}'
	}),
	update: Client.method({
		method: constants.verbs.PUT,
		url: '{+pciPod}payments/commerce/payments/cards/{cardId}?responseFields={responseFields}'
	}),
	delete: Client.method({
		method: constants.verbs.DELETE,
		url: '{+pciPod}payments/commerce/payments/cards/{cardId}'
	})
});
