

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getCurrencyLocalizations: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/?responseFields={responseFields}'
	}),
	getCurrencyExchangeRate: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}/exchangerates/{toCurrencyCode}?responseFields={responseFields}'
	}),
	getCurrencyExchangeRates: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}/exchangerates?responseFields={responseFields}'
	}),
	getCurrencyLocalization: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}?responseFields={responseFields}'
	}),
	addCurrencyLocalization: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/?responseFields={responseFields}'
	}),
	addCurrencyExchangeRates: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}/exchangerates'
	}),
	updateCurrencyExchangeRates: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}/exchangerates'
	}),
	updateCurrencyLocalization: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}?responseFields={responseFields}'
	}),
	deleteCurrencyLocalization: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}'
	}),
	deleteCurrencyExchangeRate: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/catalog/admin/currency/{currencyCode}/exchangerates/{toCurrencyCode}'
	})
});
