

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	authenticateApp: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/applications/authtickets/?responseFields={responseFields}'
	}),
	refreshAppAuthTicket: Client.method({
		method: constants.verbs.PUT,
		url: '{+homePod}api/platform/applications/authtickets/refresh-ticket?responseFields={responseFields}'
	}),
	deleteAppAuthTicket: Client.method({
		method: constants.verbs.DELETE,
		url: '{+homePod}api/platform/applications/authtickets/{refreshToken}'
	})
});
