

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../constants');


module.exports = function(Client){
	return Client.sub({
		create :Client.method({
			method: constants.verbs.POST,
			url: '{+homePod}api/commerce/payments/cards/'
		}),
		update :Client.method({
			method: constants.verbs.PUT,
			url: '{+homePod}api/commerce/payments/cards/{cardId}'
		}),
		delete :Client.method({
			method: constants.verbs.DELETE,
			url: '{+homePod}api/commerce/payments/cards/{cardId}'
		})	
	});
};
