

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants,
	AuthProvider;


module.exports = Client.sub({
	getUsers: Client.method({
		method: constants.verbs.GET,
		url: '{+homePod}api/platform/adminuser/accounts/?emailAddress={emailAddress}&startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}'
	}),
	getUserRoles: Client.method({
		method: constants.verbs.GET,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/roles?responseFields={responseFields}'
	}),
	getTenantScopesForUser : (function(getTenantScopes) { 
		return function getDefaultScope(conf) {
			AuthProvider = AuthProvider || require('../../../security/auth-provider');
			if (conf) return getTenantScopes.call(this, conf);
			if (this.context.user) return getTenantScopes.call(this, { userId: this.context.user.userId });
			return AuthProvider.addAdminUserClaims(this).then(function() {
				return getTenantScopes.call(this, { userId: this.context.user.userId });
			}.bind(this));
		};
	})(Client.method({
		scope: constants.scopes.ADMINUSER,
		method: constants.verbs.GET,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/tenants?responseFields={responseFields}'
	})),
	getUserById: Client.method({
		method: constants.verbs.GET,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/userbyid?responseFields={responseFields}'
	}),
	getUser: Client.method({
		method: constants.verbs.GET,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}?responseFields={responseFields}'
	}),
	createUser: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/adminuser/accounts/?responseFields={responseFields}'
	}),
	changePassword: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/Change-Password'
	}),
	changeUserPassword: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/Change-User-Password'
	}),
	addUserRole: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/roles/{roleId}'
	}),
	resetPassword: Client.method({
		method: constants.verbs.POST,
		url: '{+homePod}api/platform/adminuser/accounts/Reset-Password'
	}),
	updateUser: Client.method({
		method: constants.verbs.PUT,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}?responseFields={responseFields}'
	}),
	deleteUser: Client.method({
		method: constants.verbs.DELETE,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}'
	}),
	removeUserRole: Client.method({
		method: constants.verbs.DELETE,
		url: '{+homePod}api/platform/adminuser/accounts/{userId}/roles/{roleId}'
	})
});
