

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getOrderHandlingFeeRule: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}?responseFields={responseFields}'
	}),
	getOrderHandlingFeeRules: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees?responseFields={responseFields}'
	}),
	createOrderHandlingFeeRule: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees?responseFields={responseFields}'
	}),
	updateOrderHandlingFeeRule: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}?responseFields={responseFields}'
	}),
	deleteOrderHandlingFeeRule: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}'
	})
});
