

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getDeliveryAttemptSummary: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/event/push/subscriptions/{subscriptionId}/deliveryattempts/{id}?responseFields={responseFields}'
	}),
	getDeliveryAttemptSummaries: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/event/push/subscriptions/{subscriptionId}/deliveryattempts?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	})
});
