

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../client'), constants = Client.constants;

module.exports = Client.sub({
	getPublishSets: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/content/publishsets/?pageSize={pageSize}&startIndex={startIndex}&responseFields={responseFields}'
	}),
	getPublishSetItems: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/content/publishsets/{code}/items?pageSize={pageSize}&startIndex={startIndex}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	deletePublishSet: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/content/publishsets/{code}?shouldDiscard={shouldDiscard}&responseFields={responseFields}'
	}),
	addPublishSetItems: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/content/publishsets/{code}/items?responseFields={responseFields}'
	})
});
