

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getLocationGroups: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/admin/locationGroups/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	getLocationGroup: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/admin/locationGroups/{groupId}?responseFields={responseFields}'
	}),
	addLocationGroup: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/admin/locationGroups/?responseFields={responseFields}'
	}),
	updateLocationGroup: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/admin/locationGroups/{groupId}?responseFields={responseFields}'
	}),
	deleteLocationGroup: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/admin/locationGroups/{groupId}'
	})
});
