

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getAssignedDiscounts: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/assigneddiscounts'
	}),
	getCoupon: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/coupons/{couponCode}?responseFields={responseFields}'
	}),
	getCoupons: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/coupons?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	getCouponSet: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}?responseFields={responseFields}'
	}),
	assignDiscount: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/assigneddiscounts'
	}),
	addCoupons: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/coupons'
	}),
	deleteCoupons: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/coupons/remove'
	}),
	updateCouponSet: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}?responseFields={responseFields}'
	}),
	deleteCouponSet: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}'
	}),
	unAssignDiscount: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/assigneddiscounts'
	}),
	deleteCoupon: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/catalog/admin/couponsets/{couponSetCode}/coupons/{couponCode}'
	})
});
