

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getCustomerPurchaseOrderAccount: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/purchaseOrderAccount?responseFields={responseFields}'
	}),
	getCustomerPurchaseOrderTransactions: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/PurchaseOrderTransaction?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	createCustomerPurchaseOrderAccount: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/purchaseOrderAccount?responseFields={responseFields}'
	}),
	createPurchaseOrderTransaction: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/PurchaseOrderTransaction?responseFields={responseFields}'
	}),
	updateCustomerPurchaseOrderAccount: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}/purchaseOrderAccount?responseFields={responseFields}'
	}),
	deleteCustomerPurchaseOrderAccount: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/customer/accounts/internal/{accountId}/purchaseOrderAccount'
	})
});
