

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getDestinations: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/destinations'
	}),
	getDestination: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/destinations/{destinationId}?responseFields={responseFields}'
	}),
	addDestination: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/destinations?responseFields={responseFields}'
	}),
	updateDestination: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/destinations/{destinationId}?responseFields={responseFields}'
	}),
	removeDestination: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/destinations/{destinationId}'
	})
});
