

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getCheckoutNotes: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/notes'
	}),
	getCheckoutNote: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/notes/{noteId}?responseFields={responseFields}'
	}),
	createCheckoutNote: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/notes?responseFields={responseFields}'
	}),
	updateCheckoutNote: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/notes/{noteId}?responseFields={responseFields}'
	}),
	deleteCheckoutNote: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/checkouts/{checkoutId}/notes/{noteId}'
	})
});
