

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../client'), constants = Client.constants;

module.exports = Client.sub({
	getChannels: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/channels/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	getChannel: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/channels/{code}?responseFields={responseFields}'
	}),
	createChannel: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/channels/?responseFields={responseFields}'
	}),
	updateChannel: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/channels/{code}?responseFields={responseFields}'
	}),
	deleteChannel: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/channels/{code}'
	})
});
