

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../client'), constants = Client.constants;

module.exports = Client.sub({
	getManifests: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/fulfillment/shipping/manifests'
	}),

	createManifest: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/fulfillment/shipping/manifests'
	}),

	getEligibleShipments: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/fulfillment/shipping/manifests/eligibleShipments'
	}),

	getManifest: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/fulfillment/shipping/manifests/{manifestId}'
	}),

	getStorefrontShipments: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/fulfillment/storefront/shipments'
	}),

	getStorefrontShipment: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/fulfillment/storefront/shipments/{shipmentNumber}'
	}),

	createPickWave: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/pickwaves'
	}),

	getOpenPickWaves: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/pickwaves/open/{fulfillmentLocationCode}'
	}),

	getPickWave: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/pickwaves/{pickWaveNumber}'
	}),

	closePickWave: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/pickwaves/{pickWaveNumber}/closed'
	}),

	getShipmentsInPickWave: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/pickwaves/{pickWaveNumber}/shipments'
	}),

	getDefinitionImage: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/definitionImage/{containerIdOrAlias}/{processId}'
	}),

	getWorkflowProcesses: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/definitions'
	}),

	getWorkflowProcess: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/definitions/{containerIdOrAlias}/{processId}'
	}),

	getWorkflowProcessByShipmentType: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/shipmentType/{shipmentType}'
	}),

	getWorkflowProcessByShipmentTypeLocationCode: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/shipmentType/{shipmentType}/location/{locationCode}'
	}),

	getWorkflowProcessByShipmentTypeLocationGroupCode: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/processes/shipmentType/{shipmentType}/locationGroup/{locationGroupCode}'
	}),

	getShipments: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments'
	}),

	newShipment: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments'
	}),

	newShipments: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/bulk'
	}),

	getShipmentStepCountByShipmentType: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/countsByStep'
	}),

	getDashboard: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/dashboard'
	}),

	getLocationSummaryReport: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/locationSummaryReport'
	}),

	cancelShipments: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/order/{orderId}/canceled'
	}),

	searchAndReceiveTransfer: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/received/{search}'
	}),

	getSurvey: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/surveys/{id}'
	}),

	getShipment: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}'
	}),

	replaceShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}'
	}),

	deleteShipment: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}'
	}),

	getShipmentAttributes: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/attributes'
	}),

	setShipmentAttributes: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/attributes'
	}),

	getShipmentAttribute: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/attributes/{key}'
	}),

	setShipmentAttribute: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/attributes/{key}'
	}),

	deleteShipmentAttribute: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/attributes/{key}'
	}),

	backorderShipment: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/backordered'
	}),

	backorderItems: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/backorderedItems'
	}),

	backorderItemsUpdate: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/backorderedItems'
	}),

	cancelShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/canceled'
	}),

	cancelItems: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/canceledItems'
	}),

	customerAtCurbside: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/customerAtCurbside'
	}),

	customerAtStore: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/customerAtStore'
	}),

	customerCareShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/customerCared'
	}),

	customerCareItems: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/customerCaredItems'
	}),

	customerInTransit: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/customerInTransit'
	}),

	getShipmentData: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/data'
	}),

	replaceShipmentData: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/data'
	}),

	deleteShipmentData: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/data'
	}),

	destinationUpdate: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/destination'
	}),

	fulfillShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/fulfilled'
	}),

	getShipmentItemData: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/items/{lineId}/data'
	}),

	replaceShipmentItemData: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/items/{lineId}/data'
	}),

	deleteShipmentItemAttribute: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/items/{lineId}/data'
	}),

	newPackage: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/packages'
	}),

	updatePackage: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/packages/{packageId}'
	}),

	deleteShipmentPackage: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/packages/{packageId}'
	}),

	pickupItems: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/pickedUpItems'
	}),

	reassignShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/reassigned'
	}),

	reassignItems: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/reassignedItems'
	}),

	receiveTransfer: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/received'
	}),

	refreshShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/refresh'
	}),

	rejectShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/rejected'
	}),

	rejectItems: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/rejectedItems'
	}),

	retryFulfillingShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/retried'
	}),

	getSurveys: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/surveys'
	}),

	createSurvey: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/surveys'
	}),

	getTasks: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/tasks'
	}),

	execute: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/tasks/{taskName}/completed'
	}),

	revert: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/tasks/{taskName}/reverted'
	}),

	skipTask: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/tasks/{taskName}/skipped'
	}),

	transferShipment: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/transferred'
	}),

	transferItems: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/transferredItems'
	}),

	workflowDefinitionImage: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/workflow-definition-image'
	}),

	workflowInstanceImage: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/shipments/{shipmentNumber}/workflow-instance-image'
	}),
});