

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../client'), constants = Client.constants;

module.exports = Client.sub({
	getQuotes: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/quotes/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&qLimit={qLimit}&responseFields={responseFields}'
	}),
	getQuote: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/quotes/{quoteId}?responseFields={responseFields}'
	}),
	getQuoteByName: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/quotes/customers/{customerAccountId}/{quoteName}?responseFields={responseFields}'
	}),
	createQuote: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/commerce/quotes/?responseFields={responseFields}'
	}),
	updateQuote: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/commerce/quotes/{quoteId}?responseFields={responseFields}'
	}),
	deleteQuote: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/commerce/quotes/{quoteId}'
	})
});
