

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var constants = require('../../../../constants');


module.exports = function(Client){
	return Client.sub({
		sendCreateMessage :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/payments/cards/{cardId}/sync/create'
		}),
		sendDeleteMessage :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/payments/cards/{cardId}/sync/delete'
		}),
		sendUpdateMessage :Client.method({
			method: constants.verbs.POST,
			url: '{+tenantPod}api/commerce/payments/cards/{cardId}/sync/update'
		})	
	});
};
