

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../../client'), constants = Client.constants;

module.exports = Client.sub({
	getAllPackages: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/platform/appdev/apppackages/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	getPackage: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/platform/appdev/apppackages/{applicationKey}/?includeChildren={includeChildren}&skipDevAccountCheck={skipDevAccountCheck}&responseFields={responseFields}'
	}),
	getPackages: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/platform/appdev/apppackages/applications/{applicationKey}/packages/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	getApplicationSummaryChildren: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/platform/appdev/apppackages/apps/{appId}/'
	}),
	getApplicationSummaryParents: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/platform/appdev/apppackages/collection/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}'
	}),
	clonePackage: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/platform/appdev/apppackages/{applicationKey}/clone/{packageName}?responseFields={responseFields}'
	}),
	createNewCorePackage: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/platform/appdev/apppackages/create?responseFields={responseFields}'
	}),
	createPackage: Client.method({
		method: constants.verbs.POST,
		url: '{+tenantPod}api/platform/appdev/apppackages/project/?projectId={projectId}&responseFields={responseFields}'
	}),
	updatePackage: Client.method({
		method: constants.verbs.PUT,
		url: '{+tenantPod}api/platform/appdev/apppackages/{applicationKey}/?responseFields={responseFields}'
	}),
	deletePackage: Client.method({
		method: constants.verbs.DELETE,
		url: '{+tenantPod}api/platform/appdev/apppackages/{applicationKey}/'
	})
});
